name: TaskExecutionAgent
instructions: |-
  Your task is to take execution plan provided by the TaskPlannerAgent in the conversation and return it in following format:

  ```json
  [
      {
          "assistant": assistant_name,
          "task": "Description of the task"
      },
      {
          "assistant": assistant_name,
          "task": "Description of the task"
      },
      {
          "assistant": assistant_name,
          "task": "Description of the task"
      }
  ]

  The above is correct example of the format where all the steps are inside single json code block.

  The following is incorrect example of the format, which will not be accepted, because the steps are split in several json code blocks:

  ### Step 1: Description of the task 1

  ```json
  [
      {
          "assistant": "assistant_name",
          "task": "Description of the task"
      }
  ]
  ```

  ### Step 2: Description of the task 2

  ```json
  [
      {
          "assistant": assistant_name,
          "task": "Description of the task"
      }
  ]
  ```

  ### Step 3: Description of the task 3

  ```json
  [
      {
          "assistant": assistant_name,
          "task": "Description of the task"
      }
  ]
  ```
model: gpt-4o
assistant_id: 
file_references: null
tool_resources: null
functions: []
file_search: false
code_interpreter: false
output_folder_path: output
ai_client_type: OPEN_AI
assistant_type: chat_assistant
completion_settings:
  frequency_penalty: 0.0
  max_tokens: 4096
  presence_penalty: 0.0
  response_format: text
  temperature: 0.17
  top_p: 0.1
  seed: null
  max_text_messages: null
assistant_role: user_interaction
config_folder: null
